### ISSUE TITLE
findDOMNode  问题 , Electron +   @arco-design/web-react 2.55.1 

### ISSUE THREAD

**Issue by eachann1024** [arco-design/arco-design#2359] opened 2023-11-13 08:01 UTC
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.55.1
- **Framework version:** "@types/react": "^18.2.20",     "@types/react-dom": "^18.2.7",
- **Browser:** chrome119.0.0.0
- **Reproduction Link:** https://github.com/eachann1024/ReactElectron/tree/dev - src/pages/home/home.tsx

## What is expected?
不提示
node:internal/process/task_queues:140 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of ResizeObserverComponent2 which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here

## Steps to reproduce
引入 Tooltip 使用就会提示 findDOMNode
 import { Card, Avatar, Link, Typography, Space, Tooltip } from '@arco-design/web-react'
	return (
		<div className="m4">
			{/* // {clipboard}  key={index} */}
			{clipboards.length
				? clipboards.map((item) => {
						return (
							<Tooltip key={item.content} content={item.date}>
								<Card hoverable className="mb-2">
									<div className="ellipsis">{item.content}</div>
								</Card>
							</Tooltip>
						)
				  })
				: undefined}
		</div>
	)
}

**Comment by PengJiyuan** [comment] 2023-11-16 08:33
目前避免不了 findDOMNode 的报错，直接废弃会导致不能向下兼容。你看能不能把 Strict Mode 关掉呢？

**Comment by yinkaihui** [comment] 2024-01-05 08:04
Duplicate of #81

**Closed by yinkaihui** 2024-01-05 08:04 UTC
